# Generated by Django 5.0.2 on 2024-03-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_editora_alter_categoria_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
